---
- name: check for composer installation
  stat:
    path: "{{ php.composer.path }}/composer"
  register: composer_stat

- name: download composer
  become: true
  script: files/install_composer.sh
  unsafe_writes: true
  when: not composer_stat.stat.exists

- name: move composer globally
  become: true
  command: mv composer.phar {{ composer_path }}/composer
  when: not composer_stat.stat.exists

- name: set permissions on composer
  become: true
  file:
    path: "{{ composer_path }}/composer"
    mode: "a+x"
  when: not composer_stat.stat.exists

- name: "composer self-update"
  composer:
    command: self-update
    global_command: yes
  register: composer_self_update
  changed_when: "not composer_self_update.stdout|search('You are already using composer version')"
